# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tr.base.models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('rows', tr.base.models.RichTextRowBlock()),), blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Rich text page',
                'verbose_name_plural': 'Rich text pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
