# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tr.base.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0033_auto_20170418_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('full_size_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('description', wagtail.wagtailcore.blocks.TextBlock(required=False)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(required=False))))), ('section', wagtail.wagtailcore.blocks.StreamBlock((('header', wagtail.wagtailcore.blocks.StructBlock((('header_type', wagtail.wagtailcore.blocks.IntegerBlock(max_value=6, min_value=1, required=True)), ('header_text', wagtail.wagtailcore.blocks.CharBlock(required=True))))), ('rows', tr.base.models.RichTextRowBlock())))), ('separator', tr.base.models.SeparatorBlock()), ('carousel', tr.base.models.CarouselBlock())), blank=True)),
            ],
            options={
                'verbose_name': 'Rich text Page',
                'verbose_name_plural': 'Rich text Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
