# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tr.base.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Collection')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Gallery Page',
                'verbose_name_plural': 'Gallery Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='richtextpage',
            options={'verbose_name': 'Rich text Page', 'verbose_name_plural': 'Rich text Pages'},
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('header', wagtail.wagtailcore.blocks.StructBlock((('header_type', wagtail.wagtailcore.blocks.IntegerBlock(max_value=6, min_value=1, required=True)), ('header_text', wagtail.wagtailcore.blocks.CharBlock(required=True))))), ('rows', tr.base.models.RichTextRowBlock())), blank=True),
        ),
    ]
