# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormField',
            new_name='ContactFormField',
        ),
    ]
